name: "07 - Using Expressions"

on: 
    push:
        branches:
            - main
    workflow_dispatch:
        inputs: 
            debug:
                type: boolean 
                default: false 
run-name: >- 
    if [[ ${{ inputs.debug == true }}]] then; 
    'ON'
    else
    'OFF'
    fi

jobs:
    echo: 
        runs-on: ubuntu-latest 
        steps:
            - name: '[debug] Print start-up data' 
              if: ${{ inputs.debug == true }}
              run: | 
                echo "Triggered by: ${{ github.event_name }}"
                echo "Branch: ${{ github.ref }}"
                echo "Commit SHA: ${{ github.sha }}"
                echo "Runner OS: ${{ runner.os }}" 

            - name: "[debug] Print when triggered from main"
              if: ${{ (inputs.debug == true) && (github.ref == 'refs/heads/main') }}
              run: |
                echo "I was trigggered from main."

            - name: Greeting
              run: | 
                echo "Hello, world"


